/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Interfaces.Mensaje;
import Interfaces.InicioU;
import Interfaces.InicioA;
import Metodos.MetodosUsuario;

/**
 *
 * @author apinodominguez
 */
public class Registro extends javax.swing.JFrame {

   

    String nombreUser = "0";
    
    
    
    MetodosUsuario objM = new MetodosUsuario();
    InicioU objU = new InicioU();
    InicioA objA = new InicioA();
    Mensaje objMen = new Mensaje();
    
    
    
    
    public Registro() {
        initComponents();
    }

     public String getNombreU() {
        return nombreUser;
    }

    public void setNombreU(String nombreUser) {
        this.nombreUser = nombreUser;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiquetaU = new javax.swing.JLabel();
        textoU = new javax.swing.JTextField();
        etiquetaCon = new javax.swing.JLabel();
        botonA = new javax.swing.JToggleButton();
        botonR = new javax.swing.JToggleButton();
        botonC = new javax.swing.JToggleButton();
        textoC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaU.setText("USUARIO:");

        etiquetaCon.setText("CONTRASEÑA:");

        botonA.setText("ACEPTAR");
        botonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAActionPerformed(evt);
            }
        });

        botonR.setText("REGISTRARSE");
        botonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRActionPerformed(evt);
            }
        });

        botonC.setText("CANCELAR");
        botonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonA, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonR)
                        .addGap(12, 12, 12)
                        .addComponent(botonC, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(etiquetaCon))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(etiquetaU))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoU, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(etiquetaU)
                .addGap(18, 18, 18)
                .addComponent(textoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etiquetaCon)
                .addGap(18, 18, 18)
                .addComponent(textoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonA)
                    .addComponent(botonR)
                    .addComponent(botonC))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAActionPerformed
        String nombreU = objM.usuarioExiste(textoU.getText());
        String contraseña = objM.contraseñaExiste(textoC.getText());
        String tipoU = objM.tipoUsuario(nombreU);
        if(textoU.getText().isEmpty() || textoC.getText().isEmpty()){
            objMen.setVisible(true);
            objMen.setMensaje("Debes introducir ambos campos para continuar");
        }
        else{
            if(textoU.getText().equals(nombreU) && textoC.getText().equals(contraseña)){
                if("U".equals(tipoU)){
                    objU.setVisible(true);
                    setVisible(false);
                }
                if("A".equals(tipoU)){
                    objA.setVisible(true);
                    setVisible(false);
                }
                setNombreU(nombreU);
                objU.setVariables(nombreU, contraseña);
            }    
            else{
                objMen.setVisible(true);
                objMen.setMensaje("El usuario o la contraseña son incorrectos");
            }
        }        
    }//GEN-LAST:event_botonAActionPerformed

    private void botonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonCActionPerformed

    private void botonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRActionPerformed
        String nombreU = objM.usuarioExiste(textoU.getText());
        if(!textoU.getText().isEmpty() && !textoC.getText().isEmpty()){
            if(!"0".equals(nombreU)){
                objMen.setVisible(true);
                objMen.setMensaje("El nombre de usuario ya existe, elige otro");
                textoU.setText("");
            }
            else{
                objM.registrarse(textoU.getText(), textoC.getText(),"U");
                objMen.setVisible(true);
                objMen.setMensaje("El usuario se ha introducido correctamente");
            }
        }
        else{
                objMen.setVisible(true);
                objMen.setMensaje("Introduce ambos campos para continuar");
        }
    }//GEN-LAST:event_botonRActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonA;
    private javax.swing.JToggleButton botonC;
    private javax.swing.JToggleButton botonR;
    private javax.swing.JLabel etiquetaCon;
    private javax.swing.JLabel etiquetaU;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textoC;
    private javax.swing.JTextField textoU;
    // End of variables declaration//GEN-END:variables
}
